title: Junk Drawer
description: For all those little papers scattered across your desk
permalink: /blog/:year/:month/:day/:title

repository: benknoble/benknoble.github.io
github: [metadata]
encoding: UTF-8
kramdown:
  input: GFM
  hard_wrap: false
future: false
jailed: false
gfm_quirks: paragraph_end

exclude:
  - serve
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - notes
  - .ackrc
  - .gitignore

plugins:
  - jekyll-feed

defaults:
  -
    scope:
      path: _posts
      type: posts
    values:
      layout: post
  -
    scope:
      path: ""
      type: pages
    values:
      layout: page
