title: Junk Drawer
description: For all those little papers scattered across your desk
# permalink: pretty
permalink: /:categories/:year/:month/:day/:title/
author: benknoble

url: https://benknoble.github.io
repository: benknoble/benknoble.github.io
disqus_shortname: https-benknoble-github-io
encoding: UTF-8
kramdown:
  input: GFM
  hard_wrap: false
future: false
jailed: false
gfm_quirks: paragraph_end
github: [metadata]

exclude:
  - Gemfile
  - Gemfile.lock
  - Makefile
  - README.md
  - Session.vim
  - scribblings/
  - serve
  - subs/
  - tags-list
  - vendor/

defaults:
  -
    scope:
      path: _posts
      type: posts
    values:
      layout: post
      authors: [D. Ben Knoble]
  -
    scope:
      path: ""
      type: pages
    values:
      layout: page
  -
    scope:
      path: _writings
      type: writings
    values:
      layout: writing
      authors: [D. Ben Knoble]
  -
    scope:
      path: _workshops
      type: workshops
    values:
      layout: workshop
      authors: [D. Ben Knoble]

collections:
  writings:
    output: true
  workshops:
    output: true

feed:
  collections:
    - writings

gist:
  noscript: false
