title: Junk Drawer
description: For all those little papers scattered across your desk
# permalink: pretty
permalink: /:categories/:year/:month/:day/:title/
author: benknoble

repository: benknoble/benknoble.github.io
encoding: UTF-8
kramdown:
  input: GFM
  hard_wrap: false
future: false
jailed: false
gfm_quirks: paragraph_end

exclude:
  - serve
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - notes
  - .ackrc
  - .gitignore

plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jemoji
  - jekyll-mentions
  - jekyll-sitemap

defaults:
  -
    scope:
      path: _posts
      type: posts
    values:
      layout: post
  -
    scope:
      path: ""
      type: pages
    values:
      layout: page
