#! /usr/bin/env bash

set -euo pipefail

tags() {
  ack --md -hQ 'tags: [' \
    | tr -d '"'\' \
    | sed -Ee 's/tags: \[|]$//g' -e 's/,/\'$'\n''/g' \
    | sed -Ee 's/^[[:space:]]*|[[:space:]]*$//g' -e '/^[[:space:]]*$/d' \
    | sort \
    | uniq -c
}

main() {
  filter=(cat)
  if (($# > 0)) ; then
    filter=(grep "$@")
  fi
  tags | "${filter[@]}"
}

main "$@"
