name: CI
on: [push]

jobs:
  build-and-test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x
      - name: Lint site
        run: make lint
