name: CI
on: [push]

jobs:
  build-and-test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04, macos-latest]

    steps:
      - uses: actions/checkout@v1
      - run: |
          bundle install
          jekyll doctor
          jekyll build --profile
