name: Deploy to pages
on:
  push:
    branches:
      - master

jobs:
  deploy_pages:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install Racket
        uses: Bogdanp/setup-racket@v0.11
        with:
          architecture: 'x64'
          distribution: 'full'
          variant: 'CS'
          version: '8.2'

      - name: Install Racket deps
        run: raco pkg install scribble-lp2-manual

      - name: Setup ruby
        uses: ruby/setup-ruby@v1.76.0
        with:
          ruby-version: '3.0'
          bundler-cache: true

      - name: Build
        run: make _site BUILD_OPTS=--trace

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages
          folder: _site
